### PR TITLE
[config] add templates section.

### PR DESCRIPTION
**Pull request by aitboudad**
This allow to override default payum templates in config file here is an example:

```yaml
payum:
    templates:
            layout: layout.html.twig
            obtain_credit_card: payment\obtainCreditCard.html.twig

### CODE REVIEW

**Comment by makasim** [comment]
I dont see a real value in this option. as you can simply overwrite parameters. and also what about other templates that comes from klarna or stripe?

**Comment by aitboudad** [comment]
Bundles like FOSUserBundle, SonataAdmin allow overwrite templates in config, not sure why but for me parameter is the best place to overwrite template.

 > what about other templates that comes from klarna or stripe?

Not sure how to deal with this, what do you propose?

**Comment by makasim** [comment]
> Not sure how to deal with this, what do you propose?

Just keep it as is now. There are already parameters that you can overwrite, like https://github.com/Payum/PayumBundle/blob/master/Resources/config/payum.xml#L26, or https://github.com/Payum/PayumBundle/blob/master/Resources/config/payment/klarna_checkout.xml#L16

**Comment by makasim** [comment]
I dont really against of adding this to the config but I dont see how we can configure payment specific templates like stripe or klarna have. allowing to edit only core ones does not look like as a consistent solution.

**Comment by aitboudad** [comment]
Agreed :+1:

**Pull request closed without merging**
