### PR TITLE
Added symfony 5 into travis

### PR DESCRIPTION
**Pull request by Tetragramat**
Solves part of #503 
Package dunglas/symfony-lock was [deprecated](https://github.com/dunglas/symfony-lock).
So I used SYMFONY_REQUIRE added into symfony/flex. See https://github.com/symfony/flex/pull/409#issuecomment-412794585

### CODE REVIEW

**Comment by Tetragramat** [comment]
I expected for symfony 5 builds to fall but not because of phpunit requirements. phpunit/phpunit needs be at least ^6.0

**Comment by makasim** [comment]
fyi: symfony 3 could be dropped.

**Comment by Tetragramat** [comment]
fyi (For Your Information) ... that means only information or should I drop symfony 3 support in this PR? Same with phpunit version?

**Comment by Tetragramat** [comment]
I'll take that as yes.

**Comment by makasim** [comment]
that would be great if you drop it .

**Comment by Tetragramat** [comment]
Ok, done. Symfony 5 builds failed as expected.

**Comment by Tetragramat** [comment]
It's all I can do. I don't believe I will be able to fix all compatibility errors with symfony 5.
Only thing I can think of what could be done in this PR is to bump php require to be in sync with minimal symfony requirement which is ^7.1.3

**Comment by makasim** [comment]
> Only thing I can think of what could be done in this PR is to bump php require to be in sync with minimal symfony requirement which is ^7.1.3.
> And bump minimal req for symfony to ^4.4 so things like this:

Ok

**Comment by Tetragramat** [comment]
I think it's ready for review/merge.

**Pull request merged**
