### PR TITLE
Symfony 4 compatibility

### PR DESCRIPTION
**Pull request by nicolasricci**
* Update template path for debugger

### CODE REVIEW

**Comment by umpirsky** [comment]
Thanks for working on this! Any updates?

**Comment by makasim** [comment]
Will this work for for SF 2\3?

**Comment by nicolasricci** [comment]
@umpirsky well this is actually the only change required I believe for Symfony 4 compatibility. Other issue discussed is the doctrine type json_array but it is in Payum core bundle and I am waiting to hear back from @makasim on this. https://github.com/Payum/Payum/issues/684.
I am going to update the comment on this PR and it is then good for review/merge.

**Comment by nicolasricci** [comment]
@makasim yes i believe this is compatible with Symfony 2/3.
https://symfony.com/doc/2.8/templating.html#referencing-templates-in-a-bundle
https://symfony.com/doc/3.4/templating.html#referencing-templates-in-a-bundle

**Comment by makasim** [comment]
@nicolasricci thanks for your work. LGTM 

Just let me know when it is ready to be merged.

**Comment by nicolasricci** [comment]
@makasim good to merge for me 👍

**Pull request merged**
