### PR TITLE
Feat: support symfony6

### PR DESCRIPTION
**Pull request by Chris53897**
Hi,

this PR will close https://github.com/Payum/PayumBundle/issues/539

I applied some recommendations from PhpStorm-IDE.
Only the untitests are executed. i did not make a real test with an existing project.

Info: I marked some tests as incomplete. These are related to form.factory that needs a session under Symfony 6.
These tests need  to be rewritten, but i do not know how.  I guess it is related to the config-option `csrf_protection: true`.
But other tests need this config to be true.
Best way (i read about) is to rewrite the tests in a request-context. But i do not know how to do this.

Greetz

### CODE REVIEW

**Comment by Chris53897** [comment]
I updated composer.json for outdated repos and not needed dependencies for tests.
The required php-ext are required by the packages themself.
Now we have no outdated repos `composer outdated`. Only `psr/log 2.0.0 3.0.0 Common interface for logging libraries`
but only as long as payum has a new release.

**Comment by ancient-spirit** [comment]
Thank you for your effort, I hope Payum will fully support symfony6

**Comment by Chris53897** [comment]
Payum/Core itself does not depend on symfony (only in dev).
https://packagist.org/packages/payum/core

@pierredup Is this PR going in the right direction? Any suggestions to move this forward?

**Comment by pierredup** [comment]
@Chris53897 Thanks for all the effort on this. I'm going to keep this open for a bit to see where https://github.com/Payum/Payum/issues/928 goes. If we release a new major version of Payum/Payum, then the next major version of Payum/PayumBundle should support the Payum version (so there might be more changes required in this repo before we can tag a new major version)

**Comment by Fl0ux** [comment]
I would like to try your pull request, and maybe give some help if needed, but I cannot find a way to install it.
I tried this : 
```
"require": {
    "payum/payum-bundle": "feature/support-symfony6"
}
"repositories": [
    {
        "type": "git",
        "url": "git@github.com:Chris53897/PayumBundle.git"
    }
]
```
But I get this error : 
`Could not parse version constraint feature/support-symfony6: Invalid version string "feature/support-symfony6"`
Any idea how to fix it ?

**Comment by pierredup** [comment]
@Fl0ux You can add the `dev-` prefix to the version constraint, which is what Composer uses to install branches

```json
"require": {
    "payum/payum-bundle": "dev-feature/support-symfony6"
}
```

**Comment by Chris53897** [comment]
@pierredup was faster with responding ;)
You will run maybe into 2 problems. One with psr/log version. (if you use it in a real project)
Second will be masterRequest() vs mainRequest() in Symfony-Bridge from payum/core.
I will try to send PRs for this these week.

**Comment by Chris53897** [comment]
PR to close the problem getMasterRequest() vs getMainRequest() https://github.com/Payum/Payum/pull/934

**Comment by Chris53897** [comment]
@pierredup It will take a while until https://github.com/Payum/Payum/issues/928 will result in 2.x.

I would prefer to get symfony 6 up and running with this bundle and Payum/Core.
And after Payum/Core 2.x is finished we could create a new (major) version of this bundle according to changes in Payum/Core 2.x.

WDYT?

**Comment by Chris53897** [comment]
@Fl0ux I made a change to composer.json to allow an install with dev-1.x branch. This will be reverted after 1.7.1 is released.

I did a quicktest and it looks like it works. But our application needs adjustments, so i can not verify at the moment.
Can you please help with testing?

**Comment by Chris53897** [comment]
I did a test with onetime payment via saferpay-gateway and creditcard. It worked. Next step is to test a twotime payment.

@Fl0ux Did you found some time to make some tests?

**Comment by Chris53897** [comment]
@pierredup Sorry to nag you. Is there any update on this topic?

**Comment by Zales0123** [comment]
Hello @pierredup 👋 Do you have any perspective on when this change could be merged and released? :) We would definitely need it in Sylius ([issue](https://github.com/Sylius/Sylius/issues/13274) already linked) in the nearest future. Thanks in advance! 🚀 🖖

**Review by pierredup — APPROVED** [review]

**Comment by pierredup** [comment]
Sorry that it took this long, I contemplated the way forward with the various versions (for PHP and Symfony), and decided to not do a major release at the moment, but release a new 2.x version, which includes support for Symfony 6, as well as keeping support for Symfony 4 and 5.

The reasons for this, is because Symfony 4.4 is still in active maintenance, so I don't want to drop support for it at the moment, and also don't want to maintain 2 versions of the bundle (2.x for SF 4 and 5, and 3.0 for SF 6). Also, the changes required to support Symfony 4 - 6 is not a lot, so it should not be a big burden to maintain it all in a single version in the interim (until the next major version bump, which will definitely drop PHP < 8). Lastly, I think if we drop support for PHP 7 and support PHP 8 (or 8.1) only, then there are a lot more features that we can add and make more use of the new language feature. Which is why I want to work on Payum V2 first, which will support PHP 8.1+ only, but re-architect some of the internals as well, and provide a bit more features. After that, then PayumBundle 3.0 can come with support for Payum V2 only.

@Chris53897 Thanks for all the effort on this PR! I'm going to merge this now, but will hold off on a release for about a week, so that I can first test this with various projects to ensure nothing is broken. If there are no issues, then a 2.5 release with this changes can be expected any time next week.

**Comment by Chris53897** [comment]
@pierredup 
Thanks for the explanation.
My employers main goal is to use it with symfony 6 in production.
After that is done, i will try to help with Payum V2. And PayumBundle V3.


Please do not forget to bump this version after payum has a new tag.
Otherwise the bug with psr/log is still there. (and can only be used if the project has psr/log version 1). So it will not work with Symfony 6 in my eyes.
https://github.com/Payum/PayumBundle/blob/master/composer.json#L41

Commit that fixes that. But i guess this commit is lost? Sorry i lost track.
https://github.com/Chris53897/Payum/commit/46ed47d106e50c96b250d7d7cbfb117cfab03f41

https://github.com/Payum/Payum/blob/1.x/composer.json

**Comment by pierredup** [comment]
@Chris53897 That commit has been picked to the `1.7.x` branch (https://github.com/Payum/Payum/tree/1.7.x). I'm sure it should have been released with 1.7.2, but since I missed it. I'll release 1.7.3 then which will then include that change.

> After that is done, i will try to help with Payum V2. And PayumBundle V3.

It would be awesome to get some assistance on this. I've started working on some improvements for V2 and will start creating a few draft PRs over the next couple of weeks

**Comment by Chris53897** [comment]
Great. Thanks

**Pull request merged**
