### PR TITLE
[WIP] added EventDispatcherExtension.

### PR DESCRIPTION
**Pull request by aitboudad**
- [ ] Test
- [ ] Update doc

### CODE REVIEW

**Comment by makasim** [comment]
btw, what was your use case for this extension.

**Comment by aitboudad** [comment]
It's just another way to extend the payment with custom logic and 
I think symfony users use events in many cases ( Extend some functionality or add some logic)
and I see some advantage here like:
    - no need to implement ExtensionInterface
    - we can choose priority of execution

**Comment by makasim** [comment]
that sounds resanoble to me

**Comment by aitboudad** [comment]
closed in favor https://github.com/Payum/Payum/pull/294

**Pull request closed without merging**
