### PR TITLE
improve documentation for config reference

### PR DESCRIPTION
**Pull request by sohelzerdoumi**
I fixed the default configuration cause you didn't defined any token storage for security section

### CODE REVIEW

**Comment by makasim** [comment]
According to the sandbox (which is working) your change is not correct.  https://github.com/makasim/PayumBundleSandbox/blob/master/app/config/payum.yml#L32

Could you please provide more info on this issue.

**Comment by sohelzerdoumi** [comment]
Yeah sorry i made a mistake in nodes order.
However, according to your config exemple:
https://github.com/Payum/PayumBundle#configure

You didn't precise any token storage type (filesystem, doctrine etc ...) under payum.security.token_storage.Payum\Core\Model\Token

**Comment by makasim** [comment]
The storage is ORM: `{ doctrine: orm }`.

**Comment by sohelzerdoumi** [comment]
i am talking about this:
https://github.com/Payum/PayumBundle#configure

i made a dummy copy/paste of this configuration and i got 
Unrecognized options "storage_dir, id_property" under payum.security.token_storage.Payum\Core\Model\Token"

**Comment by makasim** [comment]
Got it, Thanks for your help

**Comment by sohelzerdoumi** [comment]
You welcome. 
Thx for your Bundle ;)

**Pull request merged**
