### PR TITLE
Fix key conflict when using payum.gateway_factory tag

### PR DESCRIPTION
**Pull request by erichard**
We can't have 2 name attributes when tagging a service.

### CODE REVIEW

**Comment by makasim** [comment]
What are you trying to fix? Could you explain it a bit more?

**Comment by erichard** [comment]
Yeah sorry, I was a bit in a hurry... 

There is a problem with an example in the payum-bundle documentation. In the "container tag" chapter , the "Gateway factory tag" section is

```
# app/config/config.yml

services:
    acme.foo_gateway_factory:
        class: Payum\Core\GatewayFactory
        tags:
            - { name: payum.gateway, name: foo, human_name: Foo }
```

You can't use `name` twice here.

**Comment by makasim** [comment]
I think the doc is a bit wrong. it has to be something like:

```
- { name: payum.gateway, factory: foo, human_name: Foo }
```

or 

```
- { name: payum.gateway, gateway: foo, human_name: Foo }
```

**Comment by erichard** [comment]
The code is using `name` also. It's what the PR try to fix. But it has deeper implication as the name key is used elsewhere.

**Comment by lucasgranberg** [comment]
Its also kind of a symfony bug as the tests seems to pass with name in them. There is somekind of hidden symfony magic that unsets the name key and passes the rest of the attributes to the compiler. This PR also needs documentation updates.

**Comment by makasim** [comment]
It is how YAML behave, From the spec it uses the first definition and ignore others

**Comment by makasim** [comment]
https://github.com/symfony/symfony/pull/10902

**Comment by makasim** [comment]
in master

**Pull request closed without merging**
