### PR TITLE
move storage factory init from PayumBundle::build to PayumExtension::load

### PR DESCRIPTION
**Pull request by lsmith77**

### CODE REVIEW

**Comment by makasim** [comment]
@lsmith77 Does it work for you?

**Comment by lsmith77** [comment]
it fixes the issue I encountered .. but hoping that the travis tests reveal if this creates other issues .. 
I tried to figure out from the commit history, why you previously didn't already have this code in the extension, since this seems like the logical place ..

**Comment by makasim** [comment]
for ref https://github.com/Sylius/Sylius/pull/8979#issuecomment-346766802

**Comment by lsmith77** [comment]
ok looks better now .. but didn't really do a manual test to confirm that everything is still working.

**Pull request merged**
